language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode

gemfile:
  - gemfiles/default-with-activesupport.gemfile
  - gemfiles/json.gemfile
  - gemfiles/yajl.gemfile

matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/yajl.gemfile

notifications:
  email:
    on_success: never

sudo: false
