AllCops:
  Exclude:
    - db/schema.rb

CollectionMethods:
  PreferredMethods:
    find: detect
    inject: reduce
    collect: map
    find_all: select

DotPosition:
  EnforcedStyle: trailing

LineLength:
  Max: 80

StringLiterals:
  EnforcedStyle: double_quotes
