fail_on_violations: true

rubocop:
  config_file: .rubocop.yml
  version: 0.59.2

scss:
  config_file: .scss-lint.yml

eslint:
  version: 5.7.0

reek:
  enabled: true
  config_file: .reek

flog:
  enabled: true
