# For explanations / options see here:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.3
  # Ignore rails directories.
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'script/**/*'
    - 'lib/tasks/**/*'

Rails:
  Enabled: true

OutputSafety:
  Enabled: false

# Use `fail` to signal exceptions; use `raise` to rethrow exceptions.
Style/SignalException:
  Enabled: false

# Use `raise ClassName, "message"` instead of `raise ClassName.new(message)`.
Style/RaiseArgs:
  Enabled: true

# Use one space between the method name and the first argument.
Style/SpaceBeforeFirstArg:
  Enabled: false

# Don't use self.method when method would suffice.
Style/RedundantSelf:
  Enabled: false

# Require a space inside block arguments:
# Foo.map{ |x| x }
Style/SpaceInsideBlockBraces:
  Enabled: true

# Require a space before a block:
# Foo.map {|x| x}
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Prefer the use of `lambda.call(x)` over `lambda.(x)`
Style/LambdaCall:
  Enabled: false

# Require documentation comments.
Documentation:
  Enabled: false

# Warn for methods longer than this number of lines.
Metrics/MethodLength:
  Max: 20

# Warn for classes longer than this number of lines.
Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Warn for methods more complex than this score.
Metrics/PerceivedComplexity:
  Max: 30

Metrics/AbcSize:
  Max: 30

# Ensure file names are snake_case.
Style/FileName:
  Enabled: true

# Prefer early return statements over if statements
Style/GuardClause:
  Enabled: false

# Whitelist our redis global variables.
Style/GlobalVars:
  AllowedVariables:
    - $redis_conn
    - $redis

Style/EmptyLinesAroundClassBody:
  Enabled: false

# Prefer nested definitions over compact definitions:
# module Foo ; class Bar ... ; end ; end
# class Foo::Bar ; end
Style/ClassAndModuleChildren:
  Enabled: false

# Align second line parameters with their counterparts on the first line.
Style/AlignParameters:
  Enabled: false

# multiline statements should be indented.
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# allow 'and' and 'or' operators, but not in conditionals.
Style/AndOr:
  EnforcedStyle: conditionals

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 8

# don't say that `bot?` should be attr_reader.
Style/TrivialAccessors:
  AllowPredicates: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent
