language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - ruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
before_script:
  - rake compile
