AllCops:
  Include:
  - "**/*.gemspec"
  - "**/*.podspec"
  - "**/*.jbuilder"
  - "**/*.rake"
  - "**/*.opal"
  - "**/Gemfile"
  - "**/Rakefile"
  - "**/Capfile"
  - "**/Guardfile"
  - "**/Podfile"
  - "**/Thorfile"
  - "**/Vagrantfile"
  - "**/Berksfile"
  - "**/Cheffile"
  - "**/Vagabondfile"
  Exclude:
  - "vendor/**/*"
  - "db/schema.rb"
  - "db/migrate/*"
  RunRailsCops: false
  DisplayCopNames: false
  StyleGuideCopsOnly: false
