language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
