ENABLE_HTTPS = ENV.fetch("ENABLE_HTTPS")
GITHUB_TEAM_NAME = ENV.fetch("HOUND_GITHUB_USERNAME")
MAX_COMMENTS = ENV.fetch("MAX_COMMENTS").to_i
RESQUE_RETRY_DELAY = ENV.fetch("RESQUE_RETRY_DELAY", 30).to_i
