cache: bundler
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-2.2.3
notifications:
  recipients:
    - cowboyd@thefrontside.net
before_install:
  - gem update --system 2.1.11
script: bundle exec rake compile spec
