-
  name: thoughtbot
  logo: companies/thoughtbot.png
-
  name: Mixpanel
  logo: companies/mixpanel.png
-
  name: Rails Girls
  logo: companies/rails-girls.png
-
  name: Airbrake
  logo: companies/airbrake.png
-
  name: Salesforce
  logo: companies/salesforce.png
-
  name: Joomla!
  logo: companies/joomla.png
-
  name: rackspace
  logo: companies/rackspace.png
-
  name: Middleman
  logo: companies/middleman.jpg
-
  name: Dropbox
  logo: companies/dropbox.png
-
  name: SUSE
  logo: companies/suse.png
-
  name: HP
  logo: companies/hp.png
-
  name: BBC News
  logo: companies/bbc-news.png
-
  name: Treehouse
  logo: companies/treehouse.png
-
  name: CodeShip
  logo: companies/codeship.png
-
  name: Turing School
  logo: companies/turing-school.png
-
  name: Envy Labs
  logo: companies/envy-labs.png
-
  name: shubox.io
  logo: companies/shubox.jpg
-
  name: Wealthsimple
  logo: companies/wealthsimple.png
-
  name: Yahoo
  logo: companies/yahoo.png
-
  name: Mozilla
  logo: companies/mozilla.png
-
  name: Elastic
  logo: companies/elastic.png
-
  name: MeUndies
  logo: companies/meundies.png
-
  name: GitLab
  logo: companies/gitlab.png
-
  name: Ship.io
  logo: companies/shipio.png
-
  name: Zendesk
  logo: companies/zendesk.png
-
  name: Intuit
  logo: companies/intuit.png
-
  name: Namely
  logo: companies/namely.png
-
  name: Percona
  logo: companies/percona.png
-
  name: Envoy
  logo: companies/envoy.png
-
  name: 18F
  logo: companies/18f.png
-
  name: Heroku
  logo: companies/heroku.png
-
  name: Netguru
  logo: companies/netguru.png
-
  name: Lumosity
  logo: companies/lumosity.png
-
  name: Blendtec
  logo: companies/blendtec.png
